version: '3'
services:
  nginx:
    image: nginx
    container_name: smart-store-nginx
    hostname: nginx
    ports:
      - 60080:60080
    volumes:
      - "./dist/smart-store-front/:/opt/cloud-gate-smart-store-front"
      - "./configs/nginx/cloud-gate-smart-store-front.conf:/etc/nginx/conf.d/default.conf"
      - /var/log/nginx:/var/log/nginx
